### ISSUE TITLE
报错了。。用的win10的Ubuntu子系统

### ISSUE THREAD

**Issue by BourbonZhang** [hanc00l/wifitest#3]
bourbon@DESKTOP-ULUIG0O:/mnt/c/Users/v/Desktop/wifitest-master/wifitest-master$ python wifitest.py
Total KEYS 10
Traceback (most recent call last):
  File "wifitest.py", line 177, in <module>
    main()
  File "wifitest.py", line 171, in main
    auto_test(keys,timeout,result_file)
  File "wifitest.py", line 111, in auto_test
    iface = get_wifi_interface()
  File "wifitest.py", line 10, in get_wifi_interface
    if len(wifi.interfaces()) <= 0:
  File "/home/bourbon/.local/lib/python2.7/site-packages/pywifi/wifi.py", line 42, in interfaces
    for interface in wifi_ctrl.interfaces():
  File "/home/bourbon/.local/lib/python2.7/site-packages/pywifi/_wifiutil_linux.py", line 281, in interfaces
    for f in sorted(os.listdir(CTRL_IFACE_DIR)):
OSError: [Errno 2] No such file or directory: '/var/run/wpa_supplicant'
bourbon@DESKTOP-ULUIG0O:/mnt/c/Users/v/Desktop/wifitest-master/wifitest-master$ python wifitest.py -m m -k top10.txt
Total KEYS 10
Traceback (most recent call last):
  File "wifitest.py", line 177, in <module>
    main()
  File "wifitest.py", line 173, in main
    manual_test(keys,timeout,result_file)
  File "wifitest.py", line 137, in manual_test
    iface = get_wifi_interface()
  File "wifitest.py", line 10, in get_wifi_interface
    if len(wifi.interfaces()) <= 0:
  File "/home/bourbon/.local/lib/python2.7/site-packages/pywifi/wifi.py", line 42, in interfaces
    for interface in wifi_ctrl.interfaces():
  File "/home/bourbon/.local/lib/python2.7/site-packages/pywifi/_wifiutil_linux.py", line 281, in interfaces
    for f in sorted(os.listdir(CTRL_IFACE_DIR)):
OSError: [Errno 2] No such file or directory: '/var/run/wpa_supplicant'

**Comment by hanc00l** [comment]
建议你还是用虚拟机装一个linux吧，子系统不等于linux，特别是涉及到一些内核及驱动方面的

**Comment by BourbonZhang** [comment]
嗯嗯，好的谢谢
